# Schema for the configuration files of the Chat AI module.
chat_ai.settings:
  type: config_object
  label: 'Chat AI settings'
  mapping:
    api_key:
      type: string
      label: 'Open AI Api Key'
    api_org:
      type: string
      label: 'Open AI Organization'
    supabase_key:
      type: string
      label: 'The Supabase API Key'
    supabase_url:
      type: string
      label: 'The Supabase Project REST URL'
    include:
      type: string
      label: 'Settings for the types/bundles to include on index.'
